

//GET lista de usuarios (funciona)
GET http://localhost:3000/api/users

###
//POST par 1 usuario (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "John Doe",
    "age": 25,
    "email": "john.doe@example.com",
    "password": "securepassword",
    "role": "user"
}

###

//POST par 1 usuario (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "el vigilante",
    "age": 25,
    "email": "john.elvigilante@example.com",
    "password": "securepassword",
    "role": "user"
}

###


//POST para estructura de datos final
//actualmente con test-user (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "John",
  "apellidos": "Doe",
  "alias": "JD",
  "cargo": "alumno",
  "role": "usuario",
  "email": "john.doe@u-tad.com",
  "password": "password123",
  "grado": "alumno"
}

###

//POST para estructura de datos final
//actualmente con test-user (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "antonio",
  "apellidos": "clash",
  "alias": "AS",
  "cargo": "departamento",
  "email": "john.doe@u-tad.com",
  "password": "password123",
  "grado": "alumno"
}



###


//POST para estructura de datos final
//actualmente con test-user ( NO funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "aaaa",
  "apellidos": "aaa",
  "alias": "a",
  "cargo": "departamento",
  "role": "creador",
  "email": "de.crea@u-tad.com",
  "password": "password123",
  "grado": "alumni"
}

######


//POST COORDINADOR
// (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "Jonnn",
  "apellidos": "Doooo",
  "alias": "Jowi",
  "cargo": "coordinador",
  "email": "jowii@u-tad.com",
  "password": "password123"
}


###
//POST COORDINADOR
// (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "SARA",
  "apellidos": "RADE",
  "alias": "swi",
  "cargo": "departamento",
  "email": "sara@u-tad.com",
  "password": "password123"
}



###
###
//POST ALUMNI
// (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "julio",
  "apellidos": "gomez",
  "alias": "sjuls",
  "cargo": "alumni",
  "email": "juls@live.u-tad.com",
  "password": "password123"
}



###
###
//POST ALUMNI
// (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "pepito",
  "apellidos": "perez",
  "alias": "pepe",
  "cargo": "alumni",
  "email": "pepe@live.u-tad.com",
  "password": "password123",
  "notificarAparicionDeNombre" : true,
  "notificarProyectoAceptado": false
}



###
###
//POST PROFESOR
// (funciona)
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "jara",
  "apellidos": "mamen",
  "alias": "trunks",
  "cargo": "alumno",
  "email": "jara.mamen@u-tad.com",
  "password": "password123"
}



###
###
//POST TRABAJO
// (no funciona)
POST http://localhost:3000/api/trabajos HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "titulo": "proyecto1",
  "titulacion": "inso",
  "anocreacion": 2024,
  "autores": "larys,wokis,telkis",
  "docentesImplicados": "profesor,dumbeldore,voldemort",
  "asignatura": "hacking",
  "resumen": "es una proyecto que se basa en lorem ipsum",
  "enlace": "www.loreloremacumacu.com",
  "premios": "premios2024",
  "palabrasClave": ["antia", "lorem", "ipsum", "proyecto", "2024", "premios", "asignatura", "hacking"],
  "resultadofinal": {
    "url": "asdfasdfasdf",
    "filename": "parecetrue"
  }
}





###
POST http://localhost:3000/api/trabajos HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "titulo": "proyecto2",
  "titulacion": "inso",
  "anocreacion": 2024,
  "autores": ["65ec901a5ffee9064e706cf9"],
  "docentesImplicados": "profesor,dumbeldore,voldemort",
  "asignatura": "hacking",
  "resumen": "es una proyecto que se basa en lorem ipsum",
  "enlace": "www.loreloremacumacu.com",
  "premios": "premios2024",
  "palabrasClave": ["antia", "lorem", "ipsum", "proyecto", "2024", "premios", "asignatura", "hacking"],
  "resultadofinal": {
    "url": "asdfasdfasdf",
    "filename": "parecetrue"
  }
}


###

###
// registro de usuario
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "alba",
    "apellidos": "alba",
    "alias": "blue",
    "cargo": "alumno",
    "email": "blue@gmail.com",
    "password": "passwordthefrog",
    "notificarAparicionDeNombre": true,
    "notificarProyectoAceptado": true
}

###

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "blue@gmail.com",
    "password": "passwordthefrog"
  
}

###
//para cambiar el role hace un update
//http://localhost:3000/api/auth/update/blue@gmail.com(userEMAIL)
//necesita el token de autenticacion(admin)
PUT http://localhost:3000/api/auth/update/blue@gmail.com HTTP/1.1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWYwMTNkZTJlZjljZjA2MjJlY2Y2OGEiLCJlbWFpbCI6ImJsdWVAZ21haWwuY29tIiwiaWF0IjoxNzEwMjM1NzA5LCJleHAiOjE3MTAyNDI5MDl9.MHXhXrK7TIQDOpiuMCFdBWcyejpnwkGJjvyl9Yq-aS8

{
    "role":"admin"
}


###
