
GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "John Doe",
    "age": 25,
    "email": "john.doe@example.com",
    "password": "securepassword",
    "role": "user"
}

###


POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "el vigilante",
    "age": 25,
    "email": "john.elvigilante@example.com",
    "password": "securepassword",
    "role": "user"
}

###